import { afterEach, describe, expect, it, vi } from "vitest";
import { isTauri, mediaUrl, wavObjectUrl } from "./tauri";

afterEach(() => {
  delete (globalThis as Record<string, unknown>).window;
  vi.unstubAllGlobals();
});

describe("isTauri", () => {
  it("is false outside a browser window", () => {
    expect(isTauri()).toBe(false);
  });
  it("is false in a plain browser without the Tauri bridge", () => {
    (globalThis as Record<string, unknown>).window = {};
    expect(isTauri()).toBe(false);
  });
  it("is true when the Tauri internals are injected", () => {
    (globalThis as Record<string, unknown>).window = { __TAURI_INTERNALS__: {} };
    expect(isTauri()).toBe(true);
  });
});

describe("mediaUrl", () => {
  it("passes paths through untouched outside Tauri so the web preview still renders", () => {
    expect(mediaUrl("/covers/book.jpg")).toBe("/covers/book.jpg");
  });
});

describe("wavObjectUrl", () => {
  it("wraps generated bytes in an explicit WAV blob for WebKit playback", async () => {
    const createObjectURL = vi.fn<(blob: Blob) => string>(() => "blob:generated-audio");
    vi.stubGlobal("fetch", vi.fn(async () => new Response(new Uint8Array([82, 73, 70, 70]))));
    vi.stubGlobal("URL", { createObjectURL });

    await expect(wavObjectUrl("/cache/sentence.wav")).resolves.toBe("blob:generated-audio");
    const blob = createObjectURL.mock.calls[0]?.[0];
    if (!blob) throw new Error("createObjectURL did not receive a blob");
    expect(blob).toBeInstanceOf(Blob);
    expect(blob.type).toBe("audio/wav");
    expect(blob.size).toBe(4);
  });
});
